### ISSUE TITLE
Add image attributions for full-slide background images

### ISSUE THREAD

**Issue by amanire** [isovera/reveal.js#1]
Images can be added full-screen with the `data-background-image` attribute. The text of the attribute should can then be wrapped with an element with the `attribution` CSS class. Since the slide is `<section>` element and not a `<figure>` element, I'm not sure what the appropriate markup is here. 

<img width="647" alt="Screen Shot 2019-03-15 at 11 41 24 AM" src="https://user-images.githubusercontent.com/1299537/54443585-493c0180-4717-11e9-977f-41a72617458a.png">

Here is an example using a div:

```html
<section data-background-image="images/niko-lienata-1183354-unsplash.jpg" data-background-color="#000">
  <div class="attribution">Photo by <a href="https://unsplash.com/photos/TyxvEjPzXgw">Niko Lienata</a> on Unsplash</div>
</section>
```

**Comment by benjifisher** [comment]
Please provide a complete HTML snippet so that I can test this properly.

**Comment by amanire** [comment]
I've updated the description. Using markdown, I think that would be something like this:

```html
<section data-markdown data-background-image="images/niko-lienata-1183354-unsplash.jpg">
  Photo by [Niko Lienata](https://unsplash.com/photos/TyxvEjPzXgw) on Unsplash <!-- .element: class="fragment" -->
</section>

```

**Comment by benjifisher** [comment]
@amanire:

I tried pasting that into one of my presentations, and the background image did not appear. (I used one of my own images.) Can you give a link to a live example?

**Comment by amanire** [comment]
http://amanire.github.io/isw/#/3

There is a blip when it first loads then repositions from the bottom which I don't like. Maybe a delayed opacity transition could sweep that under the rug.

**Comment by amanire** [comment]
To see the fade-in, which masks the abrupt repositioning, you have to load the previous slide and then proceed to the next slide.

http://amanire.github.io/isw/#/2 (then click spacebar)
